services:
  - type: web
    name: hacker-typer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hacker_typer.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hacker_typer.settings
